"""Point-in-time-safe analysis primitives for US Stock Helper."""

from .breadth import (
    BREADTH_VERSION,
    AdvanceDeclineResult,
    BreadthPoint,
    NewHighLowResult,
    PercentAboveMAResult,
    advance_decline_line,
    new_high_low_differential,
    percent_above_moving_average,
)
from .evidence import EvidencePacket, freeze_evidence_packet
from .forecasting import (
    CalibrationStatus,
    ScenarioCase,
    ScenarioForecast,
    ScenarioKind,
    build_scenario_forecast,
)
from .indicators import (
    MACDSeries,
    MACDValue,
    ema_series,
    macd,
    macd_series,
    moving_average,
    moving_average_series,
    rsi,
    rsi_series,
    warmup_ema_series,
    wilder_atr,
)
from .models import (
    CapitalFlowPoint,
    Direction,
    EvidenceKind,
    EvidenceRecord,
    Horizon,
    MarketContext,
    OHLCVBar,
    ParticipationBar,
    RiskPreference,
)
from .participation import build_participation_bars
from .patterns import (
    TD_SETUP_VERSION,
    MagicNineSignal,
    PatternKind,
    PatternSignal,
    TDSetupResult,
    detect_double_bottom,
    detect_head_and_shoulders,
    detect_ma5_pullback,
    magic_nine,
    td_setup,
    three_bar_fractals,
)
from .risk import (
    AnalyticalAction,
    RiskPlan,
    ShortBorrowSnapshot,
    build_risk_plan,
)
from .scoring import (
    ADVISER_SCORE_CAP,
    FactorContribution,
    FeatureSet,
    HardGate,
    ScoreResult,
    data_freshness_budget,
    extract_horizon_features,
    score_horizon,
)
from .temporal import select_bars_as_of, select_evidence_as_of
from .volatility import (
    VOLATILITY_VERSION,
    VolatilityEstimate,
    bars_per_year,
    estimate_annualized_volatility,
)
from .trend import (
    DRAGON_TREND_VERSION,
    DragonTrendResult,
    TrendState,
    TrendTransition,
    dragon_trend,
)

__all__ = [
    "ADVISER_SCORE_CAP",
    "AdvanceDeclineResult",
    "AnalyticalAction",
    "BREADTH_VERSION",
    "BreadthPoint",
    "CalibrationStatus",
    "CapitalFlowPoint",
    "DRAGON_TREND_VERSION",
    "Direction",
    "DragonTrendResult",
    "EvidenceKind",
    "EvidencePacket",
    "EvidenceRecord",
    "FactorContribution",
    "FeatureSet",
    "HardGate",
    "Horizon",
    "MACDSeries",
    "MACDValue",
    "MagicNineSignal",
    "MarketContext",
    "NewHighLowResult",
    "OHLCVBar",
    "ParticipationBar",
    "PatternKind",
    "PatternSignal",
    "PercentAboveMAResult",
    "RiskPlan",
    "RiskPreference",
    "ScenarioCase",
    "ScenarioForecast",
    "ScenarioKind",
    "ScoreResult",
    "ShortBorrowSnapshot",
    "TDSetupResult",
    "TD_SETUP_VERSION",
    "TrendState",
    "TrendTransition",
    "VOLATILITY_VERSION",
    "VolatilityEstimate",
    "advance_decline_line",
    "bars_per_year",
    "build_participation_bars",
    "build_risk_plan",
    "build_scenario_forecast",
    "data_freshness_budget",
    "detect_double_bottom",
    "detect_head_and_shoulders",
    "detect_ma5_pullback",
    "dragon_trend",
    "ema_series",
    "estimate_annualized_volatility",
    "extract_horizon_features",
    "freeze_evidence_packet",
    "macd",
    "macd_series",
    "magic_nine",
    "moving_average",
    "moving_average_series",
    "new_high_low_differential",
    "percent_above_moving_average",
    "rsi",
    "rsi_series",
    "score_horizon",
    "select_bars_as_of",
    "select_evidence_as_of",
    "td_setup",
    "three_bar_fractals",
    "warmup_ema_series",
    "wilder_atr",
]
