"""Fixed, versioned plain-language readings for the quant surfaces.

Franz is a quant-finance novice. Every number this package computes has to
answer, in plain Chinese: 这是什么 / 现在说明什么 / 什么情况下这个判断作废
(docs/superpowers/plans/2026-08-15-quant-foundations-plain-language.md). This
module is the reviewed vocabulary that answers the first two questions; the
third (失效条件) is assembled by the caller alongside the actual served
numbers, because it is honest, already-typed data (sample sizes, thresholds,
missing reasons) that belongs with the result, not with static prose.

Three-layer contract (the plan's own words):
  1. 一句话白话结论 -- ``PlainReading.headline``. Varies by *state*.
  2. 展开解释 -- ``PlainReading.explanation``. What the indicator measures,
     with a lived-world analogy. Fixed *per indicator* (not per state) --
     every state of one indicator shares the same explanation text, because
     the mechanism does not change, only the current reading does.
  3. 数字层 -- value, sample size, 失效条件. Never stored here; it comes from
     the actual result object (``RelativeVolumeResult.ratio``,
     ``VolatilityEstimate.sample_size``, ...), which the caller already has.

白话不喊单: no reading generated by this module may contain an instruction to
act. ``PlainReading.__post_init__`` enforces this at *construction* time --
not just in a test -- so a banned verb anywhere in a shipped headline or
explanation breaks the import of this module (and therefore the whole
``us_stock_helper_core`` package), rather than shipping quietly.

Completeness: every ``classify_*`` function maps its result type to a state
key drawn from a finite, explicitly enumerated domain (ratio buckets, count
buckets, direction, perfected...). A value outside that documented domain
raises ``ValueError`` -- classification never guesses and never falls back
to jargon. Every state a ``classify_*`` function can produce has a
``PlainReading`` in the matching ``*_READINGS`` dict (or, for Magic Nine's
per-count headline, a template rendered by its own ``*_reading`` function);
``tests/test_plain_language.py`` exercises every state in that domain against
the real classify function and asserts a reading comes back, so a new state
introduced without copy fails that test (and, for the banned-verb guard,
fails at import time regardless of whether a test ever runs).

Per-symbol wiring note (RVOL / range volatility): as of this module's
introduction, ``rvol.py`` and the ``parkinson``/``garman_klass`` estimators
in ``volatility.py`` are not yet part of any per-symbol wire payload --
that wiring is a separate, later task (see the plan's Task 5/6 split). This
module's ``RVOL_READINGS`` and ``VOLATILITY_READINGS`` exist and are fully
tested now specifically so that later wiring task only has to classify a
served result and look up a reading, never author copy under time pressure.
"""

from __future__ import annotations

from dataclasses import dataclass

from .breadth import PercentAboveMAResult
from .models import Direction
from .patterns import MagicNineSignal, TDSetupResult
from .relative_strength import SectorRelativeStrength
from .rvol import RelativeVolumeResult
from .volatility import VolatilityEstimate


PLAIN_LANGUAGE_VERSION = "plain-language-v1"

# 白话不喊单: a generated reading may describe what an indicator measures and
# its current state; it may never instruct an action. Enforced in
# PlainReading.__post_init__, not only in a test.
BANNED_VERBS: tuple[str, ...] = ("买入", "卖出", "加仓", "抄底", "梭哈")


@dataclass(frozen=True, slots=True)
class PlainReading:
    """Layers 1-2 of the three-layer contract: headline + explanation."""

    headline: str
    explanation: str

    def __post_init__(self) -> None:
        if not self.headline.strip():
            raise ValueError("a plain-language reading requires a headline")
        if not self.explanation.strip():
            raise ValueError("a plain-language reading requires an explanation")
        for verb in BANNED_VERBS:
            if verb in self.headline:
                raise ValueError(
                    f"plain-language headline must never contain {verb!r}: "
                    f"{self.headline!r}"
                )
            if verb in self.explanation:
                raise ValueError(
                    f"plain-language explanation must never contain {verb!r}: "
                    f"{self.explanation!r}"
                )


# ---------------------------------------------------------------------------
# RVOL (rvol.py, rvol-tod-v1): ratio buckets + every unavailable reason the
# module actually emits.
# ---------------------------------------------------------------------------

_RVOL_LIGHT_MAX = 0.7
_RVOL_NORMAL_MAX = 1.3
_RVOL_MODERATE_HIGH_MAX = 2.0

_RVOL_EXPLANATION = (
    "RVOL 比较的是「现在这个时间点」的累计成交量，和过去同一时间点的历史平均累计"
    "成交量——不是和昨天全天比，也不是和今天开盘到现在的均值比，而是同一根时钟"
    "指针位置的对比。打个比方：不是看你今天一共走了多少步，而是看你平时早上"
    "九点半这一刻通常已经走了多少步，今天这一刻又走了多少步。开盘时间太短、或"
    "历史场次不够时不给出比值，因为凑出来的『正常』看起来像测量结果，其实只是"
    "没有数据。"
)

RVOL_READINGS: dict[str, PlainReading] = {
    "rvol-light": PlainReading(
        headline="现在的成交量比平时同一时间明显缩量，交投比较清淡。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-normal": PlainReading(
        headline="现在的成交量和平时同一时间差不多，属于正常范围。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-moderate-high": PlainReading(
        headline="现在的成交量比平时同一时间温和放量，交投略微活跃。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-heavy": PlainReading(
        headline="现在的成交量比平时同一时间明显放量，交投显著活跃。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-unavailable-no-data": PlainReading(
        headline="成交量对比暂不可用：这个时间点还没有已完成的K线。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-unavailable-early-session": PlainReading(
        headline="成交量对比暂不可用：开盘时间太短，比较还不可靠。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-unavailable-insufficient-history": PlainReading(
        headline="成交量对比暂不可用：历史场次不够，凑不出可信的基准。",
        explanation=_RVOL_EXPLANATION,
    ),
    "rvol-unavailable-zero-baseline": PlainReading(
        headline="成交量对比暂不可用：历史同一时间点的成交量基准为空。",
        explanation=_RVOL_EXPLANATION,
    ),
}


def classify_rvol(result: RelativeVolumeResult) -> str:
    """Map an ``RelativeVolumeResult`` to one of ``RVOL_READINGS``'s keys.

    Raises ``ValueError`` if the result's ``missing_reason`` does not match
    any of the four reasons ``time_of_day_relative_volume`` actually emits --
    a new unavailable reason introduced there must add copy here, not fall
    through to a guess.
    """

    if result.quality_status == "unavailable":
        reason = result.missing_reason or ""
        if reason.startswith("no completed bars"):
            return "rvol-unavailable-no-data"
        if reason.startswith("early session"):
            return "rvol-unavailable-early-session"
        if reason.startswith("insufficient history"):
            return "rvol-unavailable-insufficient-history"
        if reason.startswith("historical baseline has no volume"):
            return "rvol-unavailable-zero-baseline"
        raise ValueError(f"rvol: unrecognized unavailable reason: {reason!r}")
    assert result.ratio is not None
    ratio = result.ratio
    if ratio < _RVOL_LIGHT_MAX:
        return "rvol-light"
    if ratio < _RVOL_NORMAL_MAX:
        return "rvol-normal"
    if ratio < _RVOL_MODERATE_HIGH_MAX:
        return "rvol-moderate-high"
    return "rvol-heavy"


def rvol_reading(result: RelativeVolumeResult) -> PlainReading:
    return RVOL_READINGS[classify_rvol(result)]


# ---------------------------------------------------------------------------
# Range volatility (volatility.py, close-to-close-realized-v1 / range-vol-v1):
# one shared regime bucketing (低/正常/温和偏高/明显偏高), applied to whichever
# estimator produced the value, plus every unavailable reason each estimator
# emits. The regime thresholds are a presentation-layer judgement call over
# an already-honest number -- they never change what the estimator computed.
# ---------------------------------------------------------------------------

_VOLATILITY_ESTIMATORS: tuple[str, ...] = ("close_to_close", "parkinson", "garman_klass")

_VOLATILITY_LOW_MAX = 0.15
_VOLATILITY_NORMAL_MAX = 0.30
_VOLATILITY_ELEVATED_MAX = 0.50

_VOLATILITY_BUCKET_HEADLINES: dict[str, str] = {
    "low": "最近这段时间的价格波动幅度偏低，走势相对平稳。",
    "normal": "最近这段时间的价格波动幅度处于正常区间。",
    "elevated": "最近这段时间的价格波动幅度温和偏高，起伏比平时明显一些。",
    "high": "最近这段时间的价格波动幅度明显偏高，起伏比平时大很多。",
    "unavailable-insufficient-sample": "波动率暂不可用：已收盘的K线数量还不够计算。",
    "unavailable-flat": (
        "波动率暂不可用：这段窗口里价格完全没有波动，无法算出有意义的数值。"
    ),
}

_VOLATILITY_EXPLANATIONS: dict[str, str] = {
    "close_to_close": (
        "这个估算只看每根K线的收盘价，和上一根收盘价之间的变化幅度——就像只记录"
        "你每天下班时体重秤上的数字，不管中间一天里怎么波动。方法简单、最常用，"
        "但看不到同一根K线内部走了多远。"
    ),
    "parkinson": (
        "这个估算看的是每根K线自己的最高价和最低价之间的距离——就像不只记体重，"
        "还记录你一天里最重和最轻的两个时刻差多少。比只看收盘价更能捕捉盘中波动，"
        "但假设价格不会跳空、不会带着趋势走。"
    ),
    "garman_klass": (
        "这个估算综合了每根K线的最高、最低、开盘和收盘价——在最高最低的基础上，"
        "再看开盘到收盘的净移动。信息更全，但同样假设没有跳空、没有隔夜跳动。"
    ),
}

VOLATILITY_READINGS: dict[str, PlainReading] = {
    f"volatility-{estimator}-{bucket}": PlainReading(
        headline=headline, explanation=_VOLATILITY_EXPLANATIONS[estimator]
    )
    for estimator in _VOLATILITY_ESTIMATORS
    for bucket, headline in _VOLATILITY_BUCKET_HEADLINES.items()
}


def classify_volatility(estimate: VolatilityEstimate) -> str:
    """Map a ``VolatilityEstimate`` to one of ``VOLATILITY_READINGS``'s keys."""

    estimator = estimate.estimator
    if estimator not in _VOLATILITY_ESTIMATORS:
        raise ValueError(f"volatility: unrecognized estimator: {estimator!r}")
    if estimate.quality_status == "unavailable":
        reason = estimate.missing_reason or ""
        if reason.startswith("insufficient sample"):
            return f"volatility-{estimator}-unavailable-insufficient-sample"
        if reason == "no price variation in the observed window":
            return f"volatility-{estimator}-unavailable-flat"
        raise ValueError(f"volatility: unrecognized unavailable reason: {reason!r}")
    assert estimate.value is not None
    value = estimate.value
    if value < _VOLATILITY_LOW_MAX:
        bucket = "low"
    elif value < _VOLATILITY_NORMAL_MAX:
        bucket = "normal"
    elif value < _VOLATILITY_ELEVATED_MAX:
        bucket = "elevated"
    else:
        bucket = "high"
    return f"volatility-{estimator}-{bucket}"


def volatility_reading(estimate: VolatilityEstimate) -> PlainReading:
    return VOLATILITY_READINGS[classify_volatility(estimate)]


# ---------------------------------------------------------------------------
# Breadth (breadth.py, breadth-v1): the same 多数走强/多数走弱/涨跌互现
# thresholds market_brief.py's own ``_breadth_label`` uses (55% / 45% of the
# universe above its own 50-day moving average), mirrored here so the
# vocabulary layer and the wire's own conclusion text never disagree.
# ---------------------------------------------------------------------------

_BREADTH_STRONG_MIN = 55.0
_BREADTH_WEAK_MAX = 45.0

_BREADTH_EXPLANATION = (
    "广度看的不是大盘指数涨了多少，而是「有多少只股票真的在跟着涨」——就像班里"
    "平均分不错，但可能只是几个学霸把分数拉高，其余同学没有进步。这里统计的是"
    "自选列表里，收盘价站在自己50日均线上方的比例：值越高，说明参与上涨的股票"
    "越多，而不是只有少数龙头在涨。这只统计自选列表，不是全市场，样本小时结论"
    "也更容易受个别股票影响。"
)

BREADTH_READINGS: dict[str, PlainReading] = {
    "breadth-strong": PlainReading(
        headline="自选列表里大多数股票都站上了自己的50日均线，参与上涨的股票较多。",
        explanation=_BREADTH_EXPLANATION,
    ),
    "breadth-weak": PlainReading(
        headline="自选列表里大多数股票都跌破了自己的50日均线，参与下跌的股票较多。",
        explanation=_BREADTH_EXPLANATION,
    ),
    "breadth-mixed": PlainReading(
        headline=(
            "自选列表里站上和跌破50日均线的股票数量差不多，涨跌互现，没有明显的"
            "一致方向。"
        ),
        explanation=_BREADTH_EXPLANATION,
    ),
    "breadth-unavailable": PlainReading(
        headline="自选广度暂不可用：历史K线不够计算50日均线。",
        explanation=_BREADTH_EXPLANATION,
    ),
}


def classify_breadth(result: PercentAboveMAResult) -> str:
    if result.quality_status == "unavailable":
        return "breadth-unavailable"
    assert result.percent_above is not None
    percent_above = result.percent_above
    if percent_above >= _BREADTH_STRONG_MIN:
        return "breadth-strong"
    if percent_above <= _BREADTH_WEAK_MAX:
        return "breadth-weak"
    return "breadth-mixed"


def breadth_reading(result: PercentAboveMAResult) -> PlainReading:
    return BREADTH_READINGS[classify_breadth(result)]


# ---------------------------------------------------------------------------
# Sector relative strength (relative_strength.py, sector-rs-v1): whether the
# leading sector in the current cross-section is actually ahead of the
# benchmark, applied by the caller to whichever ``SectorRelativeStrength``
# result it is presenting (market_brief.py applies it to the current
# leader's own record).
# ---------------------------------------------------------------------------

_SECTOR_RS_EXPLANATION = (
    "相对强弱比较的不是板块本身涨跌多少，而是它比基准（例如大盘ETF）跑赢还是"
    "跑输——就像比较两个人跑步，不看谁跑得快，看谁比自己的平时水平进步更多、"
    "又比对方多跑了几步。这里用的是板块最新收盘价相对自己均线的偏离幅度，减去"
    "基准同样的偏离幅度：差值为正说明这段时间跑赢了基准，为负说明跑输了。"
)

SECTOR_RS_READINGS: dict[str, PlainReading] = {
    "sector-rs-leading": PlainReading(
        headline="当前领先的板块跑赢了基准，相对走势偏强。",
        explanation=_SECTOR_RS_EXPLANATION,
    ),
    "sector-rs-lagging": PlainReading(
        headline="当前排名靠前的板块也没有跑赢基准，板块轮动整体偏弱。",
        explanation=_SECTOR_RS_EXPLANATION,
    ),
    "sector-rs-unavailable": PlainReading(
        headline="板块强弱暂不可用：样本不足或历史数据不够计算相对强弱。",
        explanation=_SECTOR_RS_EXPLANATION,
    ),
}


def classify_sector_rs(result: SectorRelativeStrength) -> str:
    if result.quality_status == "unavailable":
        return "sector-rs-unavailable"
    assert result.excess_return is not None
    return "sector-rs-leading" if result.excess_return > 0.0 else "sector-rs-lagging"


def sector_rs_reading(result: SectorRelativeStrength) -> PlainReading:
    return SECTOR_RS_READINGS[classify_sector_rs(result)]


# ---------------------------------------------------------------------------
# Magic Nine (patterns.py's td_setup/magic_nine, td-setup-close-4-v2):
# Task 7. Reading for the count in progress right now (direction x count
# bucket x perfected at completion), and a separate reading for the most
# recently *completed* run (direction x perfected), since counting restarts
# after a nine and the finished run is carried separately on the wire
# (``lastCompleted``). One shared explanation covers the whole mechanism --
# what TD Setup counts, what 9 suggests, what 完美 adds, what interruption
# means -- since that does not change from state to state, only the current
# reading does.
# ---------------------------------------------------------------------------

_MAGIC_NINE_EXPLANATION = (
    "神奇九转（TD Setup）数的是：收盘价连续比「4根K线之前」的收盘价更低（看跌"
    "方向）或更高（看涨方向）的次数，序列一旦中断（不再满足这个比较）就从头"
    "开始数——就像数一串连续绿灯，闯一次红灯就得重新数。数到 9 本身不是买卖"
    "信号，而是提醒这段单边走势已经持续很久，进入历史上更容易出现停顿或反转的"
    "『警惕区』，仅此而已，不代表现在这一刻一定会反转。「完美」是在数到 9 之后"
    "多看一眼第8、9根K线的最高/最低价有没有超过第6、7根——超过了才叫完美，是对"
    "这次计数的一次额外确认；不完美不代表这次计数无效，只是确认强度弱一些。"
)


def _direction_key(direction: Direction) -> str:
    if direction is Direction.BULLISH:
        return "bullish"
    if direction is Direction.BEARISH:
        return "bearish"
    raise ValueError(f"magic nine: unsupported direction: {direction!r}")


def _count_bucket(count: int) -> str:
    if 1 <= count <= 3:
        return "early"
    if 4 <= count <= 6:
        return "mid"
    if 7 <= count <= 8:
        return "late"
    raise ValueError(f"magic nine: unexpected in-progress count: {count!r}")


_MAGIC_NINE_PROGRESS_HEADLINE_TEMPLATES: dict[str, str] = {
    "magic-nine-unavailable": "神奇九转暂不可用：这次没有足够的K线数据来计数。",
    "magic-nine-no-active-run": (
        "当前没有正在进行中的九转计数：最近一次的连续比较被打断了，计数已经清零"
        "重新开始。"
    ),
    "magic-nine-bullish-early": (
        "上涨方向的九转刚数到 {count}——离『警惕反转』的 9 还早，当前只是记录"
        "趋势的持续性。"
    ),
    "magic-nine-bearish-early": (
        "下跌方向的九转刚数到 {count}——离『警惕反转』的 9 还早，当前只是记录"
        "趋势的持续性。"
    ),
    "magic-nine-bullish-mid": (
        "上涨方向的九转已经数到 {count}，过了一半但还没到 9，继续观察即可，"
        "不是操作提示。"
    ),
    "magic-nine-bearish-mid": (
        "下跌方向的九转已经数到 {count}，过了一半但还没到 9，继续观察即可，"
        "不是操作提示。"
    ),
    "magic-nine-bullish-late": (
        "上涨方向的九转数到 {count}，非常接近 9，进入需要多留意的『警惕反转』"
        "临界阶段，但仍然不是操作提示。"
    ),
    "magic-nine-bearish-late": (
        "下跌方向的九转数到 {count}，非常接近 9，进入需要多留意的『警惕反转』"
        "临界阶段，但仍然不是操作提示。"
    ),
    "magic-nine-bullish-complete-perfected": (
        "上涨方向的九转刚好数满 9，并且通过了『完美』的额外确认——是这轮单边"
        "走势持续最久、最值得留意反转风险的时刻，但依然只是提醒，不是操作提示。"
    ),
    "magic-nine-bearish-complete-perfected": (
        "下跌方向的九转刚好数满 9，并且通过了『完美』的额外确认——是这轮单边"
        "走势持续最久、最值得留意反转风险的时刻，但依然只是提醒，不是操作提示。"
    ),
    "magic-nine-bullish-complete-unperfected": (
        "上涨方向的九转刚好数满 9，但没有通过『完美』的额外确认——提醒依然成立，"
        "只是确认强度弱一些。"
    ),
    "magic-nine-bearish-complete-unperfected": (
        "下跌方向的九转刚好数满 9，但没有通过『完美』的额外确认——提醒依然成立，"
        "只是确认强度弱一些。"
    ),
    "magic-nine-bullish-complete-unknown": (
        "上涨方向的九转刚好数满 9，但这次没有进行『完美』核对，无法判断是否通过"
        "确认。"
    ),
    "magic-nine-bearish-complete-unknown": (
        "下跌方向的九转刚好数满 9，但这次没有进行『完美』核对，无法判断是否通过"
        "确认。"
    ),
}


def classify_magic_nine_progress(setup: TDSetupResult | None) -> str:
    """State of the run in progress right now (what the chart badge shows).

    ``setup`` is ``None`` when the count could not be computed at all (no
    bars); a computed ``setup`` whose ``latest`` is ``None`` is a genuine
    "no run in progress right now" answer, not the same as unavailable --
    mirrors the wire's own ``qualityStatus`` discipline (snapshot.py).
    """

    if setup is None:
        return "magic-nine-unavailable"
    signal = setup.latest
    if signal is None:
        return "magic-nine-no-active-run"
    direction = _direction_key(signal.direction)
    if not signal.completed:
        return f"magic-nine-{direction}-{_count_bucket(signal.count)}"
    if signal.perfected is True:
        return f"magic-nine-{direction}-complete-perfected"
    if signal.perfected is False:
        return f"magic-nine-{direction}-complete-unperfected"
    return f"magic-nine-{direction}-complete-unknown"


def magic_nine_progress_reading(setup: TDSetupResult | None) -> PlainReading:
    state = classify_magic_nine_progress(setup)
    template = _MAGIC_NINE_PROGRESS_HEADLINE_TEMPLATES[state]
    count = (
        setup.latest.count
        if setup is not None and setup.latest is not None
        else None
    )
    headline = template.format(count=count) if count is not None else template
    return PlainReading(headline=headline, explanation=_MAGIC_NINE_EXPLANATION)


_MAGIC_NINE_LAST_COMPLETED_READINGS: dict[str, PlainReading] = {
    "magic-nine-last-completed-none": PlainReading(
        headline="目前还没有出现过完整数到 9 的九转记录。",
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
    "magic-nine-last-completed-bullish-perfected": PlainReading(
        headline=(
            "最近一次数满 9 的九转方向是上涨，并且通过了『完美』确认——这是历史"
            "记录，不代表现在这一刻还成立。"
        ),
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
    "magic-nine-last-completed-bullish-unperfected": PlainReading(
        headline=(
            "最近一次数满 9 的九转方向是上涨，但没有通过『完美』确认——这是历史"
            "记录，不代表现在这一刻还成立。"
        ),
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
    "magic-nine-last-completed-bullish-unknown": PlainReading(
        headline=(
            "最近一次数满 9 的九转方向是上涨，但当时没有进行『完美』核对——这是"
            "历史记录，不代表现在这一刻还成立。"
        ),
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
    "magic-nine-last-completed-bearish-perfected": PlainReading(
        headline=(
            "最近一次数满 9 的九转方向是下跌，并且通过了『完美』确认——这是历史"
            "记录，不代表现在这一刻还成立。"
        ),
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
    "magic-nine-last-completed-bearish-unperfected": PlainReading(
        headline=(
            "最近一次数满 9 的九转方向是下跌，但没有通过『完美』确认——这是历史"
            "记录，不代表现在这一刻还成立。"
        ),
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
    "magic-nine-last-completed-bearish-unknown": PlainReading(
        headline=(
            "最近一次数满 9 的九转方向是下跌，但当时没有进行『完美』核对——这是"
            "历史记录，不代表现在这一刻还成立。"
        ),
        explanation=_MAGIC_NINE_EXPLANATION,
    ),
}


def classify_magic_nine_last_completed(last: MagicNineSignal | None) -> str:
    """State of the most recently completed run, carried separately on the
    wire as ``lastCompleted`` so it stays visible after counting restarts."""

    if last is None:
        return "magic-nine-last-completed-none"
    direction = _direction_key(last.direction)
    if last.perfected is True:
        return f"magic-nine-last-completed-{direction}-perfected"
    if last.perfected is False:
        return f"magic-nine-last-completed-{direction}-unperfected"
    return f"magic-nine-last-completed-{direction}-unknown"


def magic_nine_last_completed_reading(last: MagicNineSignal | None) -> PlainReading:
    return _MAGIC_NINE_LAST_COMPLETED_READINGS[
        classify_magic_nine_last_completed(last)
    ]
