"""Cross-language contract fixture generator.

F9 (see 2c54997, "fix: decode the macd series shape the gateway actually
sends"): the mobile MACD decoder and its hand-built TypeScript fixtures once
drifted together into the *same* wrong shape, so every test on both sides of
the wire stayed green while a real snapshot silently failed to draw. Fixtures
written by hand on one side of a language boundary can always drift with the
code that reads them; only a fixture *generated by the producing side* and
*consumed byte-for-byte by the reading side* closes that gap.

This module is the producing side: it drives ``MarketGatewayService`` through
its public, already end-to-end-tested entry points (the same construction
FakeProvider/MarketGatewayService pattern used throughout test_service.py and
test_http_gateway.py) over a fixed, deterministic bar series, and asserts the
result equals a checked-in JSON file byte-for-byte:

    fixtures/contract_snapshot_v3.json
    fixtures/contract_snapshot_v2.json

These two are the canonical cross-language contract fixtures. They are
distinct from fixtures/nvda_snapshot_redacted.json, which is an older,
hand-redacted capture kept only because other tests in this directory still
read it -- it is not regenerated from live code and must not be used as a
wire-contract reference.

Any change to the serializer -- market_gateway/snapshot.py, snapshot_v3.py,
or the indicator engines in analysis_core -- changes the generated payload
and so must regenerate the fixture in the same commit (see
REGEN_CONTRACT_FIXTURE below).

The reading side lives in
apps/mobile/src/data/__tests__/contractSnapshot.test.ts, which loads this
exact JSON file off disk and decodes it through
decodeStockSnapshotV3Envelope / decodeStockSnapshotEnvelope. A gateway shape
change that this test's byte-equality check would catch, but that a hand
maintained TypeScript fixture would not, now also breaks the mobile decode --
there is no longer a shape both sides can agree to drift into together.

To regenerate after an intentional serializer change:

    REGEN_CONTRACT_FIXTURE=1 PYTHONPATH=services/market_gateway/src:services/analysis_core \\
        python3 -m unittest services.market_gateway.tests.test_snapshot_contract_v3 -v

then re-run the suite without the env var to confirm it is now green, and
commit the regenerated fixture(s) alongside the serializer change.
"""

from __future__ import annotations

import json
import os
import unittest
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from us_stock_helper_market_gateway.models import ProviderBatch, SessionHealth
from us_stock_helper_market_gateway.service import MarketGatewayService


FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
CONTRACT_V3_PATH = FIXTURES_DIR / "contract_snapshot_v3.json"
CONTRACT_V2_PATH = FIXTURES_DIR / "contract_snapshot_v2.json"

NOW = datetime(2026, 7, 25, 4, 0, tzinfo=timezone.utc)
# The decision cutoff itself. Every provider batch is "received" a moment
# before it, and every bar/tick/flow point becomes "available" a moment
# before that: a real gateway never receives data at the exact instant it
# makes a decision, and the wire contract's own point-in-time checks (each
# row's availableAt <= its section's receivedAt <= decisionCutoff) reject a
# fixture sloppy enough to collapse all three into one timestamp.
SERIES_END = NOW - timedelta(seconds=5)
BATCH_RECEIVED_AT = NOW - timedelta(seconds=1)
SYMBOL = "NVDA"
CODE = "US.NVDA"
INTERVAL = "5m"
CANDLE_COUNT = 80


def _seed_closes(count: int) -> list[float]:
    """Deterministic and non-monotonic: the same seed ramp pinned by
    test_snapshot_indicator_series.py. Non-monotonic closes are load-bearing
    here -- a straight ramp pins RSI at 100 and never exercises MACD's sign
    changes or the pattern-shapes fractal/double-extreme detectors, which is
    exactly the kind of degenerate input that would let a wrong-but-plausible
    decode slip through undetected.
    """

    return [
        100.0 + ((index * 7) % 11) - 5.0 + index * 0.1 for index in range(count)
    ]


def _seed_candle_items(count: int) -> list[dict[str, Any]]:
    first = SERIES_END - timedelta(minutes=5 * (count - 1))
    items: list[dict[str, Any]] = []
    for index, close in enumerate(_seed_closes(count)):
        closed_at = first + timedelta(minutes=5 * index)
        items.append(
            {
                "code": CODE,
                "timeframe": INTERVAL,
                "timestamp": closed_at.isoformat(),
                "available_at": closed_at.isoformat(),
                "received_at": BATCH_RECEIVED_AT.isoformat(),
                "price_adjustment": "forward-adjusted",
                "complete": True,
                "open": close - 0.25,
                "high": close + 0.5,
                "low": close - 0.5,
                "close": close,
                "volume": 1_000.0 + index,
            }
        )
    return items


def _seed_flow_items() -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for index in range(6):
        moment = SERIES_END - timedelta(minutes=5 * (5 - index))
        items.append(
            {
                "code": CODE,
                "timestamp": moment.isoformat(),
                "available_at": moment.isoformat(),
                "session": "2026-07-24",
                "total_net": 2_400.0 * (index + 1),
                "super_net": 1_000.0 * (index + 1),
                "big_net": 800.0 * (index + 1),
                "mid_net": 400.0 * (index + 1),
                "small_net": 200.0 * (index + 1),
            }
        )
    return items


def _seed_holding_items() -> list[dict[str, Any]]:
    return [
        {
            "code": CODE,
            "period": "2026/Q1",
            "reported_at": "2026-03-31T20:00:00+00:00",
            "available_at": "2026-05-16T14:00:00+00:00",
            "institution_count": 863,
            "institution_count_change": 12,
            "shares_held": 4_192_178_205,
            "shares_held_change": -3_105_448,
            "holding_percent": 46.474,
            "holding_percent_change": 0.03,
            "source": "moomoo-delayed-institutional-disclosure",
        }
    ]


class _SeededProvider:
    """The only inputs the cross-language contract fixture depends on.

    Fixed and deterministic on purpose: changing any value here changes the
    generated payload and requires regenerating both checked-in fixtures.
    """

    def __init__(self) -> None:
        self._health = SessionHealth(
            state="healthy",
            checked_at=NOW - timedelta(seconds=2),
            source="moomoo",
        )
        self._quote = ProviderBatch(
            source="moomoo",
            received_at=BATCH_RECEIVED_AT,
            items=[
                {
                    "code": CODE,
                    "price": _seed_closes(CANDLE_COUNT)[-1],
                    "change_percent": 2.7,
                    "available_at": SERIES_END.isoformat(),
                }
            ],
        )
        self._candles = ProviderBatch(
            source="moomoo",
            received_at=BATCH_RECEIVED_AT,
            items=_seed_candle_items(CANDLE_COUNT),
        )
        self._flow = ProviderBatch(
            source="moomoo",
            received_at=BATCH_RECEIVED_AT,
            items=_seed_flow_items(),
        )
        self._holdings = ProviderBatch(
            source="moomoo",
            received_at=BATCH_RECEIVED_AT,
            items=_seed_holding_items(),
        )

    def health(self) -> SessionHealth:
        return self._health

    def quotes(self, codes: list[str]) -> ProviderBatch:
        return self._quote

    def candles(self, code: str, timeframe: str, count: int) -> ProviderBatch:
        return self._candles

    def capital_flow(self, code: str) -> ProviderBatch:
        return self._flow

    def institutional_holdings(self, code: str) -> ProviderBatch:
        return self._holdings


def _service() -> MarketGatewayService:
    return MarketGatewayService(
        _SeededProvider(),
        clock=lambda: NOW,
        session_max_age=timedelta(seconds=15),
        response_max_age=timedelta(seconds=15),
    )


def _generate_v3_payload() -> dict[str, Any]:
    return _service().stock_snapshot_v3(SYMBOL, INTERVAL, CANDLE_COUNT)


def _generate_v2_payload() -> dict[str, Any]:
    return _service().stock_snapshot(SYMBOL, INTERVAL, CANDLE_COUNT)


def _render(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


class ContractSnapshotFixtureTests(unittest.TestCase):
    def _assert_matches_fixture(self, path: Path, rendered: str) -> None:
        if os.environ.get("REGEN_CONTRACT_FIXTURE"):
            path.write_text(rendered, encoding="utf-8")
        try:
            on_disk = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            on_disk = None
        self.assertEqual(
            on_disk,
            rendered,
            f"{path.name} is stale or missing -- regenerate with "
            "REGEN_CONTRACT_FIXTURE=1 python3 -m unittest "
            "services.market_gateway.tests.test_snapshot_contract_v3 "
            "in the same commit as the serializer change that produced this diff",
        )

    def test_v3_snapshot_matches_the_checked_in_contract_fixture(self) -> None:
        payload = _generate_v3_payload()
        # A partial or unavailable snapshot would let every indicator quietly
        # degrade to null; only a live snapshot exercises MACD/RSI series,
        # magicNine and patternShapes with real, non-null values on both
        # sides of the wire.
        self.assertEqual(payload["status"], "live")
        self.assertEqual(
            payload["sections"]["technical"]["data"]["indicators"]["macd"][
                "qualityStatus"
            ],
            "live",
        )

        self._assert_matches_fixture(CONTRACT_V3_PATH, _render(payload))

    def test_v2_snapshot_matches_the_checked_in_contract_fixture(self) -> None:
        payload = _generate_v2_payload()
        self.assertEqual(
            payload["indicators"]["macd"]["qualityStatus"],
            "live",
        )

        self._assert_matches_fixture(CONTRACT_V2_PATH, _render(payload))


if __name__ == "__main__":
    unittest.main()
